config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"
  resources :prototypes do
    resources :comments,   only: :create
  end
  resources :users,        only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prototype
  belongs_to :user


  validates :text, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
#   仮に、1つのツイートに対して5つのコメントがあるとします。
# もし、そのツイートが削除されたら、それに付随する5つのコメントも削除されるべきです。
# その場合、Tweetモデル（親モデル）に関連しているCommentモデル（子モデル）のdependentオプションに、:destroyを指定します。

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #, :confirmable #←ココに追加だけ
#          deviseの初期導入時点では「confirmable」の機能は有効化されていません。
#          そのため、設定後のように末尾に「:confirmable」を追加してください。
#          [confirmable機能の有効化]
#   ↓
# [データベースへの項目追加]
# 【補足説明】それぞれの項目説明
# 今回追加した４つの項目について、どのような目的のものか少し補足します。

# カラム名	説明	入力値例
# confirmation_token	一意のランダムトークン。この値を使って認証します	KtMVn65jFxDT1qB6aY5P
# confirmed_at	ユーザーが確認リンクをクリックしたときのタイムスタンプ	2019-09-17 13:12:37
# confirmation_sent_at	confirm_tokenが生成されたときのタイムスタンプ	2019-09-17 13:06:18
# unconfirmed_email	変更後メールアドレスを認証完了まで一時的に保持。確認リンクが押された時点でemailが上書きされ、このカラムは空に（メールアドレス変更時のみ使用）	xxxxx@gmail.com
#   ↓
# [Controllerのカスタマイズ]
#   ↓
# [送信メールフォームの修正]※途中からMailerのカスタマイズへの分岐あり
#   ↓
# [confirmable機能のオプション指定]
#   ↓
# [メール送信設定]※別Qiitaに飛びます
#   ↓
# [認証メールの動作確認]

# [途中導入の注意点]※おまけ的な
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true
  has_many  :prototypes
  has_many  :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #deviceはコントローラーが編集できないためapplication.controllerにデータを引き渡す
  # ストロングパラメータをかく
  before_action :configure_permitted_parameters, if: :devise_controller? 
  #戻り値がtrueであった時のみ実行deviseのへるぱーメソッドを指定してdeviseに関するコントローラーの処理であればとしてる
  # 処理名	目的
  # :sign_in	ログイン(サインイン)の処理を行うとき
  # :sign_up	新規登録(サインアップ)の処理を行うとき
  # :account_update	アカウント情報更新の処理を行うときき
  

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :name, :profile, :occupation, :position])
  end
  # devise_parameter_sanitizer.permit(:deviseの処理名, keys: [:許可したいキー（カラム名）]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(params[:prototype_id])
    @comment = @prototype.comments.create(comment_params)
      if @comment.save
        # redirect_to "/prototypes/#{comment.prototype.id}" 
         redirect_to prototype_path(params[:prototype_id])
      else
         @prototype = @comment.prototype
         @comments = @prototype.comments.includes(:user)
        #  @comments = @prptotype.comments
        render "prototypes/show" # views/tweets/show.html.erbのファイルを参照しています。
      end
  end             
  # createメソッドは引数にキーとバリューのセットの情報を渡します。

private

    def comment_params
      params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id:  params[:prototype_id])
    end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @prototypes = Prototype.all
    # binding.pry
  end

  def new
    @prototype = Prototype.new
    # オブジェクトA ... (1)
  end

  def create
    @prototype = Prototype.new(prototype_params)
     # オブジェクトB ... (2)
     # (1)の@hogeとは別の新規のオブジェクト
       if @prototype.save
          redirect_to root_path, notice: "作成しました"
       else
        @prototype = Prototype.new(prototype_params)
        render 'new'
        # オブジェクトB
      
        # オブジェクトC
        # .newにより新規に作られたオブジェクトが@prototypeに設定される
        # バリデーションエラーはオブジェクトBが持っているが、
        # @hogeが指すのは、オブジェクトCになってしまったので
        # エラーは表示されない
       end
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    if @prototype.destroy
      redirect_to root_path
    end
  end
  
  def edit
    unless user_signed_in? && current_user.id == Prototype.find(params[:id]).user_id
      redirect_to action: :index
    else
      @prototype = Prototype.find(params[:id])
    end
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to prototype_path(@prototype.id)
    else
      # @prototype = prototype.update(prototype_params)
      render :edit
    end
  end
#---------------------------------------
  # if @item.update(item_params)
  #   redirect_to @item
  # else
  #   render :edit
  # end
#---------------------------------------
#テキスト ChatAppUser管理機能問８
# def update
#   if current_user.update(user_params)
#     redirect_to root_path
#   else
#     render :edit
#   end
# end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new #from withを使用してコメントをクリエイト「comments#create」を実行したい
    @comments = @prototype.comments.includes(:user)
  end

  private

  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image ).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # binding.pry
    # @prototypes = @user.prototypes
    # @prototypes = Prototype.where(user_id: params[:id])
    @prototypes = Prototype.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <% else %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id) %>
  <%# <%= image_tag prototype.image, class: 'card__img'%> <%#これではリンクしない#%>
  <%# <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <%# #決論  基本的にはimage_tag("#{  }")では読み込めないことがわかった 3/24%>
  <div class="card__body">
    <%= link_to prototype.title, prototype_path(prototype.id), class: :card__title%>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to "by #{User.find(prototype.user_id).name}", user_path(prototype.user_id), class: :card__user%>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form"%>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
      <% if user_signed_in? %>
        <div class="greeting">
          <%# こんにちは, %>
          <%= link_to "こんにちは#{current_user.name}さん", user_path(current_user.id), class: :greeting__link %>
        </div>
    <%# // ログインしているときは上記を表示する %>
      <% else %>

      <% end %>
        <div class="card__wrapper">
           <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
            <%= render partial: "prototype", collection: @prototypes %>
        </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する renderメソッドを利用するpartial というオプションで指定する%>
        <%# partialオプション  percial: ディレクトリ/ファイル名（_(アンダースコア）とhtml.erb.を外して）%>
        <%# loalオプション %>
        <%# #viewファイルに置いて繰り返し使用するコードを切り出して再利用する仕組みのこと %>
        <%# 命名規則として_（アンダースコアを先頭にします） %>
        <%= render partial: "form"%>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{User.find(@prototype.user_id).name}", user_path(@prototype.user_id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
          <div class="prototype__manage">
            <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
            <%= link_to "削除する", prototype_path(@prototype.id), method: :delete, class: :prototype__btn %>
          </div>
      <% end %>
        <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
        <div class="prototype__image">
          <%= image_tag @prototype.image %>
        </div>
        <div class="prototype__body">
          <div class="prototype__detail">
            <p class="detail__title">キャッチコピー</p>
            <p class="detail__message">
              <%= @prototype.catch_copy %>
            </p>
          </div>
          <div class="prototype__detail">
            <p class="detail__title">コンセプト</p>
            <p class="detail__message">
              <%= @prototype.concept %>
            </p>
          </div>
        </div>
      <%#======================================================================%>
        <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with model: [@prototype, @comment], local: true do |f| %>
              <%# model: @comment だけなら→comments_path ３月２７日%>
            <div class="field">
              <%= f.label :text_area, "コメント"%><br/>
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %>
          <% else %>
            <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
              <% @comments.each do |comment| %>
                <li class="comments_list">
                  <%= comment.text %>
                  <%= link_to User.find(comment.user_id).name, user_path(comment.user_id), class: :comment_user %><br/>
                 </li>
              <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.name %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}のプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
            <%= render partial: "prototypes/prototype", collection: @prototypes %>
      </div>
    </div>
  </div>
</div>